- import_playbook: find_amis.yml

- name: Generate users and nodes lists
  hosts: localhost
  connection: local
  become: no
  gather_facts: no
  vars_files:
    - hosting-node-ec2.yml
    - "{{ workshop_name }}-template-nodes-ec2.yml"
  tasks:
    - name: generate users list
      set_fact:
        users: "{{ users|default([]) + [ {'name': 'student' + item, 'username': 'student' + item, 'email': 'student' + item + '@example.com'} ] }}"
      with_sequence: start="{{ student_count_start }}" end="{{ student_count_end }}"
      when: student_count_start is defined and student_count_end is defined

    - name: initialize nodes variable
      set_fact:
        nodes: "{{ nodes|default([]) + [item] }}"
      with_items: "{{ hosting_nodes }}"

    - debug:
        var: nodes

    - name: generate nodes list
      set_fact:
        nodes: "{{ nodes }} + {{ [item.0] }}"
      with_nested:
        - "{{ template_nodes }}"
        - "{{ users }}"

    - debug:
      var: nodes

    - pause:

- name: provision ec2 instances
  hosts: localhost
  become: no
  roles:
    - ansible-role-ec2

- name: add hosts to groups
  hosts: localhost
  become: no
  roles:
    - create-runtime-inventory
    - generate-content

- name: configure common options on all linux nodes
  hosts: tag_app_management_lightbulb:!tag_role_hosting:!tag_role_windows
  become: yes
  remote_user: ec2-user
  become_method: sudo
  gather_facts: true
  roles:
    - user_accounts
    - common

- name: configure common options on windows domain controller
  hosts: tag_app_management_lightbulb:&tag_role_windows_domain_controller
  remote_user: Administrator
  become: no
  vars:
    ansible_port: 5986
    ansible_password: "{{ domain_admin_password }}"
    ansible_connection: winrm
    ansible_winrm_transport: basic
    ansible_winrm_server_cert_validation: ignore
  gather_facts: true
  roles:
    - windows-ad-controller

- name: configure common options on all windows workstation
  hosts: tag_app_management_lightbulb:&tag_role_windows_workstation
  remote_user: Administrator
  become: no
  vars:
    ansible_port: 5986
    ansible_password: "{{ domain_admin_password }}"
    ansible_connection: winrm
    ansible_winrm_transport: basic
    ansible_winrm_server_cert_validation: ignore
  gather_facts: true
  roles:
    - windows-common
    - windows-workstation

- name: configure common options on all windows nodes
  hosts: tag_app_management_lightbulb:&tag_role_windows_node
  remote_user: Administrator
  become: no
  vars:
    ansible_port: 5986
    ansible_password: "{{ domain_admin_password }}"
    ansible_connection: winrm
    ansible_winrm_transport: basic
    ansible_winrm_server_cert_validation: ignore
  gather_facts: true
  roles:
    - windows-common

- name: configure gitlab host
  hosts: tag_app_management_lightbulb:&tag_role_gitlab
  become: yes
  remote_user: ec2-user
  become_method: sudo
  gather_facts: true
  roles:
    - geerlingguy.gitlab

# run post-config separate to avoid handler restart issue
- name: configure gitlab host
  hosts: tag_app_management_lightbulb:&tag_role_gitlab
  become: yes
  remote_user: ec2-user
  become_method: sudo
  gather_facts: true
  roles:
    - gitlab-postconfig

- name: configure control node
  hosts: control_nodes
  become: yes
  roles:
    - control-node
    - geerlingguy.repo-epel
    - geerlingguy.nodejs
    - wetty

- name: provision tower
  hosts: tag_role_tower:&tag_app_management_lightbulb
  become: yes
  remote_user: ec2-user
  become_method: sudo
  gather_facts: true
  vars_files:
    - "group_vars/all/vars"
    - "group_vars/all/vault"
  roles:
    - provision-ansible-tower
    - tower-add-content
    - geerlingguy.repo-epel
    - geerlingguy.nodejs
    - wetty

- name: provision cfme
  hosts: tag_role_cfme:&tag_app_management_lightbulb
  become: yes
  remote_user: ec2-user
  become_method: sudo
  gather_facts: true
  vars_files:
    - "group_vars/all/vars"
    - "group_vars/all/vault"
  roles:
    - provision-cfme
    - cfme-add-provider-ec2
    - cfme-add-provider-tower

- name: setup hosting
  hosts: tag_role_hosting:&tag_app_management_lightbulb
  become: yes
  roles:
    - provision-dns-ec2
    - nginx
    - hosting-generate-html
    - hosting-upload-content

- name: email inventory to instructor
  hosts: localhost
  connection: local
  become: no
  gather_facts: no
  roles:
    - email-instructor