- import_playbook: find_amis.yml

- name: Generate users and nodes lists
  hosts: localhost
  connection: local
  become: no
  gather_facts: no
  vars_files:
    - hosting-node-ec2.yml
    - "{{ workshop_name }}-template-nodes-ec2.yml"
  tasks:
    - name: generate users list
      set_fact:
        users: "{{ users|default([]) + [ {'name': 'student' + item, 'username': 'student' + item, 'email': 'student' + item + '@example.com'} ] }}"
      with_sequence: start="{{ student_count_start }}" end="{{ student_count_end }}"
      when: student_count_start is defined and student_count_end is defined

    - name: initialize nodes variable
      set_fact:
        nodes: "{{ hosting_nodes }}"

    - name: generate nodes list
      set_fact:
        nodes: "{{ nodes }} + {{ template_nodes }}"
      with_items:
        - "{{ users }}"

    - debug:
        var: nodes

    - name: generate windows only nodes list
      set_fact:
        windows_nodes: "{{ windows_nodes|default([]) + [ item ] }}"
      with_items:
        - "{{ nodes }}"
      when: item.os_type is defined and item.os_type == 'windows'

    - debug:
        var: windows_nodes

    - name: generate linux only nodes list
      set_fact:
        linux_nodes: "{{ linux_nodes|default([]) + [ item ] }}"
      with_items:
        - "{{ nodes }}"
      when: item.os_type is not defined or item.os_type == 'linux'

    - debug:
        var: linux_nodes

- name: provision linux ec2 instances
  hosts: localhost
  become: no
  roles:
    - role: ansible-role-ec2
      nodes: "{{ linux_nodes }}"

- name: add linux hosts to groups
  hosts: localhost
  become: no
  roles:
    - create-runtime-inventory

- name: provision windows ec2 instances
  hosts: localhost
  become: no
  vars:
    ansible_port: 5986
  roles:
    - role: ansible-role-ec2
      instance_wait_connection_timeout: 600
      nodes: "{{ windows_nodes }}"

- name: add windows hosts to groups and generate content
  hosts: localhost
  become: no
  roles:
    - create-runtime-inventory
    - generate-content

- name: configure common options on all linux nodes
  hosts: tag_app_management_lightbulb:!tag_role_hosting:!tag_role_windows
  become: yes
  remote_user: ec2-user
  become_method: sudo
  gather_facts: true
  roles:
    - user_accounts
    - common

- name: change hostname on all windows nodes
  hosts: tag_app_management_lightbulb:&tag_role_windows
  remote_user: Administrator
  become: no
  vars:
    ansible_port: 5986
    ansible_password: "{{ domain_admin_password }}"
    ansible_connection: winrm
    ansible_winrm_transport: basic
    ansible_winrm_server_cert_validation: ignore
  gather_facts: true
  roles:
    - windows-hostname

- name: configure common options on windows domain controller
  hosts: tag_app_management_lightbulb:&tag_role_windows_domain_controller
  remote_user: Administrator
  become: no
  vars:
    ansible_port: 5986
    ansible_password: "{{ domain_admin_password }}"
    ansible_connection: winrm
    ansible_winrm_transport: basic
    ansible_winrm_server_cert_validation: ignore
  gather_facts: true
  pre_tasks:
    - debug:
        msg: "users list for windows ad controller role: {{ users }}"
  roles:
    - role: windows-ad-controller
      users: "{{ users }}"

- name: configure common options on all windows workstation
  hosts: tag_app_management_lightbulb:&tag_role_windows_workstation
  remote_user: Administrator
  become: no
  vars:
    ansible_port: 5986
    ansible_password: "{{ domain_admin_password }}"
    ansible_connection: winrm
    ansible_winrm_transport: basic
    ansible_winrm_server_cert_validation: ignore
  gather_facts: true
  roles:
    - windows-common
    - windows-workstation

- name: configure common options on all windows nodes
  hosts: tag_app_management_lightbulb:&tag_role_windows_node
  remote_user: Administrator
  become: no
  vars:
    ansible_port: 5986
    ansible_password: "{{ domain_admin_password }}"
    ansible_connection: winrm
    ansible_winrm_transport: basic
    ansible_winrm_server_cert_validation: ignore
  gather_facts: true
  roles:
    - windows-common

- name: configure gitlab host
  hosts: tag_app_management_lightbulb:&tag_role_gitlab
  become: yes
  remote_user: ec2-user
  become_method: sudo
  gather_facts: true
  roles:
    - geerlingguy.gitlab

# run post-config separate to avoid handler restart issue
- name: configure gitlab host
  hosts: tag_app_management_lightbulb:&tag_role_gitlab
  become: yes
  remote_user: ec2-user
  become_method: sudo
  gather_facts: true
  roles:
    - gitlab-postconfig

- name: configure control node
  hosts: control_nodes
  become: yes
  roles:
    - control-node
    - geerlingguy.repo-epel
    - geerlingguy.nodejs
    - wetty

- name: provision tower
  hosts: tag_role_tower:&tag_app_management_lightbulb
  become: yes
  remote_user: ec2-user
  become_method: sudo
  gather_facts: true
  vars_files:
    - "group_vars/all/vars"
    - "group_vars/all/vault"
  roles:
    - provision-ansible-tower
    - tower-add-content
    - geerlingguy.repo-epel
    - geerlingguy.nodejs
    - wetty

- name: provision cfme
  hosts: tag_role_cfme:&tag_app_management_lightbulb
  become: yes
  remote_user: ec2-user
  become_method: sudo
  gather_facts: true
  vars_files:
    - "group_vars/all/vars"
    - "group_vars/all/vault"
  roles:
    - provision-cfme
    - cfme-add-provider-ec2
    - cfme-add-provider-tower

- name: setup hosting
  hosts: tag_role_hosting:&tag_app_management_lightbulb
  become: yes
  roles:
    - provision-dns-ec2
    - nginx
    - hosting-generate-html
    - hosting-upload-content

- name: email inventory to instructor
  hosts: localhost
  connection: local
  become: no
  gather_facts: no
  roles:
    - email-instructor